name: KrisAbrams.com
favicon: null
layout_spectrum: 0.9254827746190131
typography_spectrum: 0.51463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090909'
    - '#ffffff'
    - '#bfbfbf'
    - '#292929'
    - '#888888'
  brandStrength: 1
  lightness: 0.8153598981443793
  saturation: 0.4375
  rhythmicContrast: 0.9660863685421646
purpose: []
