name: KrisAbrams.com
favicon: null
layout_spectrum: 0.9254827746190131
typography_spectrum: 0.3667108011431992
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9528667356353253
  lightness: 0.8153598981443793
  saturation: 0.2182367609348148
  rhythmicContrast: 0.9660863685421646
purpose: []
